### ISSUE TITLE
Non rectangular areas

### ISSUE THREAD

**Issue by jnsturgis** [jnsturgis/hard_discs2#1]

**Comment by jnsturgis** [comment]
Should have a backward compatible method for including in a configuration file a non-rectangular area. 

Rectangular areas are provided as a two number width and height.
Perhaps a line with more than 2 numbers starts a series of points for a polygonal area that ends with an empty line.
Such areas should by default be non-periodic.

Also, we should adjust the definition of the configuration file to include, or allow the inclusion of comments. Perhaps comments could be C-style /* ... */ or // to EOL.

**Comment by msidore** [comment]
Probably add a number somewhere in the beginning of the configuration file to tell the type of area ?

**Comment by jnsturgis** [comment]
Introduced new code... I think the issue is closed in the branch Not_rectangle
