### ISSUE TITLE
Log file format

### ISSUE THREAD

**Issue by jnsturgis** [jnsturgis/hard_discs2#5]
Clarify the format of the log files produced.
Separate the format from the middle of the code.
Make sure errors produce **helpful** messages in the log file.
Make efforts to have a parsable output (by gnuplot for example).

**Comment by msidore** [comment]
Draft general log file with information from the force-field and everything that also goes to stdout.
At this moment, no error goes in the log.
The "parsable output" would be a timeserie of the energy ?
