### ISSUE TITLE
Command line handling

### ISSUE THREAD

**Issue by jnsturgis** [jnsturgis/hard_discs2#6]
Tidy up the command line handling and error reporting associated with it.

**Comment by msidore** [comment]
I think this is ok.

**Comment by jnsturgis** [comment]
It doesn't end very elegantly if you don't give any options!!!! (after I managed to install boost and get it to work properly)

**Comment by jnsturgis** [comment]
Also makeconfig does not work anymore since it writes to stdout, as now write() expects a 'file name' and not a 'file handle'...

**Comment by msidore** [comment]
I'll handle makeconfig tomorrow (and find a way to make it end more elegantly with no arguments too !)

**Comment by msidore** [comment]
Default behavior handled (0 arguments). Still the scary error when there aren't enough arguments. Makeconfig ok.

**Comment by jnsturgis** [comment]
I think we are OK... until the next problem
